application: the-hat-dev
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /landing
  static_files: templates/landing.html
  upload: templates/landing.html

- url: /android/beta
  static_files: templates/android_beta.html
  upload: templates/android_beta.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /assets
  static_dir: assets

- url: /internal/.*
  script: main.app
  login: admin

- url: .*
  script: main.app


builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: django
  version: "1.4"
- name: jinja2
  version: latest
- name: numpy
  version: latest
- name: matplotlib
  version: latest
